version: '3.8'
services:
  spring-app:
    build: .
    container_name: spring-app-recipe-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-recipe-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./mysql_data:/var/lib/mysql
networks:
  app-network:
